package gui;

import gui.lib.DBPanel;
import gui.lib.DBPanelConfirmation;
import java.awt.Component;
import javax.swing.JOptionPane;
import lib.Car;

public class CarFuelDialog extends javax.swing.JDialog {

    private final Car car;

    /**
     * Creates new form CarFuelDialog
     */
    public CarFuelDialog(java.awt.Frame parent, boolean modal, Car car) {
        super(parent, modal);
        this.car = car;
        initComponents();

        this.setLocationRelativeTo(parent);
        this.setTitle("Mašinos " + car.getBrand() + " (" + car.getRegistrationNumber() + ") naudojamas kuras");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carFuelPanel1 = new gui.CarFuelPanel(true, car);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carFuelPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carFuelPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DBPanelConfirmation confirmation = new DBPanelConfirmation(this,
                new Component[] {carFuelPanel1});

        int result = confirmation.showConfirmation();
        DBPanel panelWithError = confirmation.getPanelWithError();

        if (result != JOptionPane.CANCEL_OPTION && panelWithError == null) {
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.CarFuelPanel carFuelPanel1;
    // End of variables declaration//GEN-END:variables
}
