package gui;

import gui.lib.DBCellRenderer;
import gui.lib.DBTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import lib.Car;
import lib.DatabaseObject;
import lib.Fuel;

public class CarFuelPanel extends gui.lib.DBPanel {

    private final Car car;
    private final AbstractTableModel tableModel;
    private String[] columnNames = {"Kodas", "Pavadinimas", "Naudoja"};

    private final List<Fuel> carFuels = new ArrayList<Fuel>();

    /**
     * Creates new form CompanyPanel
     */
    public CarFuelPanel() {
        this(false, null);
    }

    public CarFuelPanel(boolean autoUpdate, final Car car) {
        this.car = car;
        tableModel = new DBTableModel(columnNames, objects) {

            @Override
            public Object getObjectValue(DatabaseObject object, int row, int col) {
                Fuel fuel = (Fuel) object;
                switch (col) {
                    case 0:
                        return fuel.getCode();
                    case 1:
                        return fuel.getTitle();
                    case 2:
                        return getCarUsesFuel(fuel);
                    default:
                        return null;
                }
            }

            @Override
            public boolean setObjectValue(DatabaseObject object, Object value, int row, int col) {
                if (object != null && !object.equals(getObjectValue(object, row, col))) {
                    Fuel fuel = (Fuel) object;
                    switch (col) {
                        case 0:
                            fuel.setCode((String) value);
                            break;
                        case 1:
                            fuel.setTitle((String) value);
                        case 2:
                            if (!getCarUsesFuel(fuel)) {
                                car.addFuel(fuel);
                            } else {
                                car.removeFuel(fuel);
                            }
                            updateFuelList();
                            break;
                    }
                    return true;
                }
                return false;
            }

            @Override
            public boolean isObjectEditable(DatabaseObject object, int col) {
                if (object.isCreated()) {
                    return col > 0;
                }
                return true;
            }
        };

        if (autoUpdate) {
            resetData();
        }

        initComponents();
        fuelTable.setDefaultRenderer(Object.class, new DBCellRenderer());
    }

    private boolean getCarUsesFuel(Fuel fuel) {
        for (Fuel f : carFuels) {
            if (f.getCode().equals(fuel.getCode())) {
                return true;
            }
        }
        return false;
    }

    private void updateFuelList() {
        List<Fuel> fetchedFuels = car.fetchFuels();

        carFuels.clear();
        if (fetchedFuels != null) {
            carFuels.addAll(fetchedFuels);
        }
    }

    @Override
    public final void resetData() {
        updateFuelList();

        objects.clear();
        List<Fuel> newItems = Fuel.fetchAll();
        if (newItems != null) {
            objects.addAll(newItems);
        }
        tableModel.fireTableDataChanged();
    }

    @Override
    public void redrawData() {
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        fuelTable = new javax.swing.JTable();
        jLoadButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jSaveCompanyButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();

        fuelTable.setModel(tableModel);
        fuelTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(fuelTable);

        jLoadButton.setText("Pakrauti");
        jLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadButtonActionPerformed(evt);
            }
        });

        jAddButton.setText("Pridėti");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jSaveCompanyButton.setText("Išsaugoti");
        jSaveCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveCompanyButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("Trinti");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRemoveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSaveCompanyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLoadButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRemoveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSaveCompanyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLoadButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadButtonActionPerformed
        resetData();
    }//GEN-LAST:event_jLoadButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        Fuel fuel = new Fuel("", "");
        objects.add(fuel);

        int lastIndex = objects.size() - 1;
        tableModel.fireTableRowsInserted(lastIndex, lastIndex);
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jSaveCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveCompanyButtonActionPerformed
        saveData();
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_jSaveCompanyButtonActionPerformed

    private void jRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveButtonActionPerformed
        int[] selection = fuelTable.getSelectedRows();
        if (selection.length > 0) {
            int result = JOptionPane.showConfirmDialog(this, "Ar tikrai norite pašalinti pasirinktus įrašus?",
                    "Šalinti kurą", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {
                for (int i = selection.length - 1; i >= 0; i--) {
                    DatabaseObject object = objects.get(selection[i]);
                    if (object.destroy()) {
                        objects.remove(selection[i]);
                    }
                }

                if (selection.length > 0) {
                    tableModel.fireTableRowsDeleted(selection[0],
                            selection[selection.length - 1]);
                }
            }
        }
    }//GEN-LAST:event_jRemoveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fuelTable;
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jLoadButton;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JButton jSaveCompanyButton;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
