package gui;

import gui.lib.DBPanel;
import gui.lib.DBPanelConfirmation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lib.Trip;

public class TripEditDialog extends javax.swing.JDialog {

    private final JFrame parentFrame;
    private final Trip trip;

    /**
     * Creates new form TripDialog
     */
    public TripEditDialog(JFrame parent, boolean modal, Trip trip) {
        super(parent, modal);
        this.parentFrame = parent;
        this.trip = trip;
        initComponents();

        setTitle("Kelionė iš " + trip.getStartLocation() + " į "
                + trip.getEndLocation());

        dateLabel.setText(trip.getDateFrom() + " - " + trip.getDateUntil());
        directionLabel.setText(trip.getStartLocation() + " - " + trip.getEndLocation());

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        directionLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tripEmployeesPanel1 = new gui.TripEmployeesPanel(true, trip);
        tripCarsPanel2 = new gui.TripCarsPanel(true, trip);
        tripReceiptPanel1 = new gui.TripReceiptPanel(true, trip);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Data:");

        jLabel2.setText("Kryptis:");

        directionLabel.setText("kryptis");

        dateLabel.setText("data");

        jTabbedPane1.addTab("Važiavę darbuotojai", tripEmployeesPanel1);
        jTabbedPane1.addTab("Naudotos mašinos", tripCarsPanel2);
        jTabbedPane1.addTab("Kvitai", tripReceiptPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addComponent(directionLabel))
                        .addGap(0, 636, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(directionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DBPanelConfirmation confirmation = new DBPanelConfirmation(this,
                jTabbedPane1.getComponents());

        int result = confirmation.showConfirmation();
        DBPanel panelWithError = confirmation.getPanelWithError();

        if (result != JOptionPane.CANCEL_OPTION && panelWithError == null) {
            setVisible(false);
            dispose();
        } else if (panelWithError != null) {
            jTabbedPane1.setSelectedComponent(panelWithError);
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel directionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.TripCarsPanel tripCarsPanel2;
    private gui.TripEmployeesPanel tripEmployeesPanel1;
    private gui.TripReceiptPanel tripReceiptPanel1;
    // End of variables declaration//GEN-END:variables
}
